#!/bin/bash
testdir=$(dirname "$0")
pup=${PUP:-"${testdir}/../pup"}
cmds="${testdir}/cmds.txt"
input="${testdir}/index.html"
output="${testdir}/test_results.txt"
expected="${testdir}/expected_output.txt"
trap 'rm -f "$output"' EXIT

while true; do
  case "$1" in
    -update) mode=update;;
    *) break;;
  esac
  shift
done

while read -r t; do
  "$pup" "$t" < "$input" | shasum | while read -r sum _; do
    echo "$sum $t"
  done
done < "$cmds" > "$output"

if [[ $mode == "update" ]]; then
  mv "$output" "$expected"
  echo "$expected updated"
else
  diff "$expected" "$output" && echo "OK"
fi
